[book]
title = "Паттерны проектирования в Rust"
authors = ["the rust-unofficial authors"]
description = "Каталог паттернов проектирования, анти-паттернов и идиом в языке Rust"
language = "ru"
multilingual = false
src = "src"

[build]
create-missing = false
extra-watch-dirs = ["po", "third_party"]

[preprocessor.gettext]
after = ["links"]

[rust]
edition = "2018"

[output.html]
curly-quotes = true
default-theme = "rust"
site-url = "/patterns/"
git-repository-url = "https://github.com/lagleki/patterns"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/lagleki/patterns/edit/Russian/{path}"
additional-css = ["./language-picker.css"]

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = false

# [output.linkcheck]  # enable the "mdbook-linkcheck" renderer, disabled due to gh-actions
